### ISSUE TITLE
Handle GET Request from EHR

### ISSUE THREAD

**Issue by gdadlaney** [gdadlaney/Data-Exchange-Platform#2]
Complete the app.get(:mrn) function in hie.js -

- [x] Check the directory for the file. Use the fs.readdirSync() method(Actually done using statSync()).
- [x] If the file with given MRN does not exist, return a 404.
- [x] Add some code for user input. You ask the user to choose between 2 choices, 1) Upload a file or 2) Request a file.

**Comment by gdadlaney** [comment]
The standard .readir() method will be used in the end, due to its asynchronous nature. See how that can be implemented. The listFiles() method does the same, try to rewrite it in a way that can be used by this as well.

Discussions are welcome.

**Comment by adi0602** [comment]
Done.
Check it once.

**Comment by gdadlaney** [comment]
Alright. Good Job.
Just the part of using an aync method for checking files in the directory is left out, which is not a priority.

Closing the issue.
