### ISSUE TITLE
Improvements in handling metadata

### ISSUE THREAD

**Issue by gdadlaney** [gdadlaney/Data-Exchange-Platform#7]
The .env file must be used to store hardcoded values, like ehr_id, wherever possible. Rename the file after it is received at HIE, as files will be searched based on their MRN.

Tasks -
- [x] Create an .env file. Read ehr_id in dummy ehr, port number in hie.
- [x] Rename the uploaded file as MRN.xml
  - [x] Precondition: Check if metadata has been received.(flag)

**Comment by gdadlaney** [comment]
Problem: .env files are listed in .gitignore, won't be included in commits. Any workarounds for this?

**Comment by gdadlaney** [comment]
Renaming file is a priority since #4 depends on it. It needs it to compute the hash.

**Comment by anujpahade** [comment]
I’ll take this.
