### ISSUE TITLE
Creation of EMPI

### ISSUE THREAD

**Issue by gdadlaney** [gdadlaney/Data-Exchange-Platform#8]
In the current implementation, a record is requested given its MRN, but in the real process, the EHR doesn't have this information. It just has the patient's identification information like name, ssn. The EMPI will give us the patient's global_id, with which we can lookup the latest record in the record chain.

Tasks -
- [ ] Create a Table in MySQL with attributes as global_id, name, ssn, ...
- [ ] Add a new API endpoint(GET), accepting query params like name, ssn, zipcode, etc.
- [ ] Send a query to the DB. (try SQL procedures for abstraction)

**Comment by adi0602** [comment]
I've created the dummy data dump by phpma CLI. Please check if that works.

**Comment by gdadlaney** [comment]
Yeah, I will
